// Den synlige personlige ordliste starter tom. Det generelle danske ordforraad ligger i language-data.json.
export const DEFAULT_DATA = {
  schemaVersion: 1,
  appVersion: '0.3.1-beta1',
  words: [],
  sentences: [
    {
      id: 'starter-sentence-1',
      text: 'Jeg vil gerne have en kop kaffe.',
      keywords: ['kaffe', 'drikke', 'kop'],
      priority: 95,
    },
    {
      id: 'starter-sentence-2',
      text: 'Kaffen er for varm.',
      keywords: ['kaffe', 'varm'],
      priority: 90,
    },
    {
      id: 'starter-sentence-3',
      text: 'Kaffen er blevet kold.',
      keywords: ['kaffe', 'kold'],
      priority: 85,
    },
    {
      id: 'starter-sentence-4',
      text: 'Jeg vil ikke have mere kaffe.',
      keywords: ['kaffe', 'mere', 'ikke'],
      priority: 82,
    },
    {
      id: 'starter-sentence-5',
      text: 'Vil du lave kaffe?',
      keywords: ['kaffe', 'lave'],
      priority: 78,
    },
    {
      id: 'starter-sentence-6',
      text: 'Jeg vil gerne have et stykke kage.',
      keywords: ['kage', 'spise', 'stykke'],
      priority: 92,
    },
    {
      id: 'starter-sentence-7',
      text: 'Kagen smager godt.',
      keywords: ['kage', 'godt'],
      priority: 75,
    },
    {
      id: 'starter-sentence-8',
      text: 'Kan du hjælpe mig?',
      keywords: ['kan', 'hjælp', 'hjælpe'],
      priority: 94,
    },
    {
      id: 'starter-sentence-9',
      text: 'Kan du gentage det?',
      keywords: ['kan', 'gentage', 'spørgsmål'],
      priority: 90,
    },
    {
      id: 'starter-sentence-10',
      text: 'Kan vi tale om noget andet?',
      keywords: ['kan', 'tale', 'andet'],
      priority: 86,
    },
    {
      id: 'starter-sentence-11',
      text: 'Jeg kan ikke forstå det.',
      keywords: ['kan', 'ikke', 'forstå'],
      priority: 84,
    },
    {
      id: 'starter-sentence-12',
      text: 'Jeg kan godt høre dig.',
      keywords: ['kan', 'høre', 'godt'],
      priority: 80,
    },
    {
      id: 'starter-sentence-13',
      text: 'Jeg vil gerne hvile lidt.',
      keywords: ['hvile', 'træt', 'lidt'],
      priority: 88,
    },
    {
      id: 'starter-sentence-14',
      text: 'Vil du hjælpe mig med at flytte mit ben?',
      keywords: ['hjælp', 'flytte', 'ben'],
      priority: 88,
    },
    {
      id: 'starter-sentence-15',
      text: 'Jeg har brug for min telefon.',
      keywords: ['telefon', 'bruge', 'hente'],
      priority: 80,
    },
    {
      id: 'starter-sentence-16',
      text: 'Hvad er klokken?',
      keywords: ['tid', 'klokken', 'hvad'],
      priority: 78,
    },
    {
      id: 'starter-sentence-17',
      text: 'Hvornår kommer du igen?',
      keywords: ['hvornår', 'kommer', 'igen'],
      priority: 76,
    },
    {
      id: 'starter-sentence-18',
      text: 'Jeg vil gerne se fjernsyn.',
      keywords: ['tv', 'fjernsyn', 'se'],
      priority: 74,
    },
  ],
};
